services:
  api:
    container_name: kenzie_courses
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c "yarn migration:run && yarn dev"
  pg:
    container_name: courses_db
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5431:5432
